export const API_ENDPOINTS = {
    LOGIN_ADMIN: "http://localhost:3000/auth/login-admin",
    FORGOT_PASSWORD: "http://localhost:3000/auth/forgot-password",
    RESET_PASSWORD: "http://localhost:3000/auth/reset-password",
    ROLES: "http://localhost:3000/roles",
    MODULE: "http://localhost:3000/modules",
    MODULE_BY_ID: (id: string) => `http://localhost:3000/modules/${id}`,
    ADMIN_USERS: "http://localhost:3000/admin-management/users",
    CATALOG_PLANTS: "http://localhost:3000/catalog-plants",
    CATALOG_PLANT_BY_ID: (id: string) => `http://localhost:3000/catalog-plants/${id}`,
    PLANT_IMAGES_UPLOAD: "http://localhost:3000/plant-images/upload",
    PLANT_IMAGES_LINK: "http://localhost:3000/plant-images/link",
    PLANT_IMAGES_BY_ID: (id: string) => `http://localhost:3000/plant-images/${id}`,
    ADMIN_DEVICES: "http://localhost:3000/admin/devices",
    ADMIN_DEVICE_BY_ID: (id: string) => `http://localhost:3000/admin/devices/${id}`,
    ADMIN_DEVICE_REGENERATE_KEY: (id: string) => `http://localhost:3000/admin/devices/${id}/regenerate-key`,
    TAXONOMY: "http://localhost:3000/taxonomy",
    USERS_GENERAL_MANAGEMENT: "http://localhost:3000/users-general-management",
    PROFILE_ADMIN: "http://localhost:3000/profile-management/admin",
    PROFILE_UPDATE: "http://localhost:3000/profile-management",
    PROFILE_CHANGE_PASSWORD: "http://localhost:3000/profile-management/change-password",
    PROFILE_PHOTO: "http://localhost:3000/profile-management/profile/photo",
    FAQS: "http://localhost:3000/faqs",
    FAQS_BY_ID: (id: string) => `http://localhost:3000/faqs/${id}`,
    FAQS_BY_PARENT: (parentId: string) => `http://localhost:3000/faqs?parentId=${parentId}`,
    FAQS_IMAGES_UPLOAD: "http://localhost:3000/faqs/images",
    FAQS_IMAGES_DELETE: "http://localhost:3000/faqs/delete/images",
    MARKETPLACE_CATEGORIES: "http://localhost:3000/marketplace/categories",
    MARKETPLACE_CATEGORY_BY_ID: (id: string) => `http://localhost:3000/marketplace/categories/${id}`,
    MARKETPLACE_CATEGORIES_BY_PARENT: (parent_id: string) => `http://localhost:3000/marketplace/categories?parent_id=${parent_id}`,
    MARKETPLACE_CATEGORY_UPLOAD_IMAGE: "http://localhost:3000/marketplace/categories/upload-image",
    MARKETPLACE_CATEGORY_IMAGE: (id: string) => `http://localhost:3000/marketplace/categories/${id}/image`,
};